
package com.mycompany.practica_temperaturas;

/**
 *
 * @author carlossalcidoa
 */
public class Main extends javax.swing.JFrame {
    Celsius c;
    Kelvin k;
    Farenheit f;
    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        c = new Celsius();
        k = new Kelvin();
        f = new Farenheit();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lblValor = new javax.swing.JLabel();
        lblResultado = new javax.swing.JLabel();
        txtValor = new javax.swing.JTextField();
        txtResultado = new javax.swing.JTextField();
        btnConvertir = new javax.swing.JButton();
        rbCelsiusKelvin = new javax.swing.JRadioButton();
        rbFarenheitCelsius = new javax.swing.JRadioButton();
        rbKelvinCeslsius = new javax.swing.JRadioButton();
        rbCelsiusFarenheit = new javax.swing.JRadioButton();
        lblTitulo = new javax.swing.JLabel();
        rbKF = new javax.swing.JRadioButton();
        rbFK = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblValor.setText("Valor:");

        lblResultado.setText("Resultado:");

        txtValor.setToolTipText("");

        txtResultado.setEditable(false);

        btnConvertir.setText("Convertir");
        btnConvertir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConvertirActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbCelsiusKelvin);
        rbCelsiusKelvin.setText("Celsius - Kelvin");

        buttonGroup1.add(rbFarenheitCelsius);
        rbFarenheitCelsius.setText("Farenheit - Celsius");
        rbFarenheitCelsius.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbFarenheitCelsiusActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbKelvinCeslsius);
        rbKelvinCeslsius.setText("Kelvin - Celsius");

        buttonGroup1.add(rbCelsiusFarenheit);
        rbCelsiusFarenheit.setText("Celsius - Farenheit");

        lblTitulo.setText("Conversión entre temperaturas");

        buttonGroup1.add(rbKF);
        rbKF.setText("Kelvin - Farenheit");

        buttonGroup1.add(rbFK);
        rbFK.setText("Farenheit - Kelvin");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitulo)
                .addGap(98, 98, 98))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblResultado)
                            .addComponent(lblValor))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtResultado)
                            .addComponent(txtValor))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(btnConvertir, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbKF)
                    .addComponent(rbCelsiusFarenheit)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(rbCelsiusKelvin)
                        .addComponent(rbKelvinCeslsius))
                    .addComponent(rbFarenheitCelsius)
                    .addComponent(rbFK))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblTitulo)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblValor)
                            .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(rbCelsiusKelvin)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblResultado)
                            .addComponent(txtResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(rbKelvinCeslsius)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addComponent(rbCelsiusFarenheit)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbFarenheitCelsius)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnConvertir, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rbKF)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbFK)))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbFarenheitCelsiusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbFarenheitCelsiusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbFarenheitCelsiusActionPerformed

    private void btnConvertirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConvertirActionPerformed
        if(rbCelsiusKelvin.isSelected()){
            c.setValor(Double.parseDouble(txtValor.getText()));
            c.Celsius_Kelvin();
            txtResultado.setText(String.valueOf(c.getResultado()));
        }
        else if(rbKelvinCeslsius.isSelected()){
            k.setValor(Double.parseDouble(txtValor.getText()));
            k.Kelvin_Celsius();
            txtResultado.setText(String.valueOf(k.getResultado()));
        }
        else if(rbCelsiusFarenheit.isSelected()){
            c.setValor(Double.parseDouble(txtValor.getText()));
            c.Celsius_Farenheit();
            txtResultado.setText(String.valueOf(c.getResultado()));
        }
        else if(rbFarenheitCelsius.isSelected()){
            f.setValor(Double.parseDouble(txtValor.getText()));
            f.Farenheit_Celsius();
            txtResultado.setText(String.valueOf(f.getResultado()));
        }
        else if(rbFK.isSelected()){
            f.setValor(Double.parseDouble(txtValor.getText()));
            f.Farenheit_Kelvin();
            System.out.println(5/9);
            txtResultado.setText(String.valueOf(f.getResultado()));
        }
        else if(rbKF.isSelected()){
            k.setValor(Double.parseDouble(txtValor.getText()));
            k.Kelvin_Farenheit();
            txtResultado.setText(String.valueOf(k.getResultado()));
        }
        
    }//GEN-LAST:event_btnConvertirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConvertir;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel lblResultado;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblValor;
    private javax.swing.JRadioButton rbCelsiusFarenheit;
    private javax.swing.JRadioButton rbCelsiusKelvin;
    private javax.swing.JRadioButton rbFK;
    private javax.swing.JRadioButton rbFarenheitCelsius;
    private javax.swing.JRadioButton rbKF;
    private javax.swing.JRadioButton rbKelvinCeslsius;
    private javax.swing.JTextField txtResultado;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
