
package SRT;

import java.awt.Image;
import java.awt.Label;
import java.awt.event.ActionEvent;
import java.util.ArrayList;
import java.util.TimerTask;
import javax.swing.Timer;
import javax.swing.JOptionPane;
import javax.swing.JTabbedPane;
import javax.swing.table.DefaultTableModel;
import java.util.Random;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import javax.swing.ImageIcon;
import javax.swing.JTextField;

public class MainProgram extends javax.swing.JFrame implements KeyListener {
    
    private Timer mTimer;
    private int contloc=0;//contador local
    private int contglobal=0;//contador local
    private int tiempo=0;
    private int temprest=0;
    private int it=0;
    private int distancia=50;//distancia
    private int distancia2=50;//distancia
    private int distancia3=50;//distancia
    private int distancia4=50;//distancia
    private int distancia5=50;//distancia
    private int time=0,time2=0,time3=0,time4=0,time5=0;//CINCO NUMEROS ALEATORIOS
    private int iterator_tabla1=0;
    private int[] array=new int[5];
    private int i=0;
    private Label l1;
    //ArrayList <Proceso> procesos;
    //Proceso pr;
    
    ImageIcon imageIconPonyta= new ImageIcon("ponyta.png");
    Image imagePonyta = imageIconPonyta.getImage();
    Image modPonyta = imagePonyta.getScaledInstance(50, 50, java.awt.Image.SCALE_SMOOTH);
        
    public MainProgram(){
        
        //procesos = new ArrayList<>();
        imageIconPonyta = new ImageIcon(modPonyta);
        
        initComponents();
        mTimer = new Timer(1000, (ActionEvent e) -> {
                iniciarCronometro();  
            });
        
        addKeyListener(this);
        setFocusable(true);
        //btnIniciar.setVisible(true);
        this.setVisible(true);
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lbl1 = new javax.swing.JLabel();
        btnIniciar = new javax.swing.JButton();
        lbl2 = new javax.swing.JLabel();
        lbl3 = new javax.swing.JLabel();
        lbl4 = new javax.swing.JLabel();
        lbl5 = new javax.swing.JLabel();
        pnlMeta = new javax.swing.JPanel();
        btnPrepararse = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        jPanel2.setBackground(new java.awt.Color(102, 153, 255));

        btnIniciar.setText("INICIAR");
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });

        pnlMeta.setBackground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout pnlMetaLayout = new javax.swing.GroupLayout(pnlMeta);
        pnlMeta.setLayout(pnlMetaLayout);
        pnlMetaLayout.setHorizontalGroup(
            pnlMetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );
        pnlMetaLayout.setVerticalGroup(
            pnlMetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
        );

        btnPrepararse.setText("PREPARARSE");
        btnPrepararse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrepararseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(210, Short.MAX_VALUE)
                        .addComponent(btnPrepararse, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(btnIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(292, 292, 292))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl2)
                            .addComponent(lbl1)
                            .addComponent(lbl3)
                            .addComponent(lbl4)
                            .addComponent(lbl5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(pnlMeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnPrepararse, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(pnlMeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lbl1)
                        .addGap(69, 69, 69)
                        .addComponent(lbl2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl3)
                        .addGap(80, 80, 80)
                        .addComponent(lbl4)
                        .addGap(97, 97, 97)
                        .addComponent(lbl5)
                        .addGap(111, 111, 111))))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
        lbl1.setLocation(20, 20);
        lbl2.setLocation(20, 120);
        lbl3.setLocation(20, 220);
        lbl4.setLocation(20, 320);
        lbl5.setLocation(20, 420);
        pnlMeta.setLocation(850, 20);
        
        lbl1.setText("");
        lbl1.setIcon(imageIconPonyta);
        lbl2.setText("");
        lbl2.setIcon(imageIconPonyta);
        lbl3.setText("");
        lbl3.setIcon(imageIconPonyta);
        lbl4.setText("");
        lbl4.setIcon(imageIconPonyta);
        lbl5.setText("");
        lbl5.setIcon(imageIconPonyta);
        
        distancia=50;
        distancia2=50;
        distancia3=50;
        distancia4=50;
        distancia5=50;
        
        int n = array.length;
        for (int i = 0; i < n - 1; i++)
            for (int j = 0; j < n - i - 1; j++)
                if (array[j] > array[j + 1]) {
                    // swap arr[j+1] and arr[j]
                    int temp = array[j];
                    array[j] = array[j + 1];
                    array[j + 1] = temp;
                    
                }
        //System.out.println("Tiempo 1: " + array[0]);
        //System.out.println("Tiempo 2: " + array[1]);
        //System.out.println("Tiempo 3: " + array[2]);
        //System.out.println("Tiempo 4: " + array[3]);
        //System.out.println("Tiempo 5: " + array[4]);
        
        mTimer.start();
    }//GEN-LAST:event_btnIniciarActionPerformed

    private void btnPrepararseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrepararseActionPerformed
        lbl1.setLocation(20, 20);
        lbl2.setLocation(20, 120);
        lbl3.setLocation(20, 220);
        lbl4.setLocation(20, 320);
        lbl5.setLocation(20, 420);
        pnlMeta.setLocation(850, 20);
        
        lbl1.setText("");
        lbl1.setIcon(imageIconPonyta);
        lbl2.setText("");
        lbl2.setIcon(imageIconPonyta);
        lbl3.setText("");
        lbl3.setIcon(imageIconPonyta);
        lbl4.setText("");
        lbl4.setIcon(imageIconPonyta);
        lbl5.setText("");
        lbl5.setIcon(imageIconPonyta);
        
        i=0;
        
        l1 = new Label ("Tiempo: 0");
        l1.setLocation(50, 50);
        
        Random dado = new Random();
        time=dado.nextInt(10-5+1)+7;
        time2=dado.nextInt(10-5+1)+7;
        time3=dado.nextInt(10-5+1)+7;
        time4=dado.nextInt(10-5+1)+7;
        time5=dado.nextInt(10-5+1)+7;
        //System.out.println("Tiempo: " + time);
        //System.out.println("Tiempo2: " + time2);
        //System.out.println("Tiempo3: " + time3);
        //System.out.println("Tiempo4: " + time4);
        //System.out.println("Tiempo5: " + time5);
        
        //for(int i=0;i<5;i++){
        //    if(time2==time){time2+=1;}
        //    if(time3==time2||time3==time){time3+=1;}
        //    if(time4==time3||time4==time2||time4==time){time4+=1;}
        //    if(time5==time4||time5==time3||time5==time2||time5==time){time5+=1;}
        //}
        
        
        array[0]=time;
        array[1]=time2;
        array[2]=time3;
        array[3]=time4;
        array[4]=time5;
        
        System.out.println("Tiempo 1: " + array[0]);
        System.out.println("Tiempo 2: " + array[1]);
        System.out.println("Tiempo 3: " + array[2]);
        System.out.println("Tiempo 4: " + array[3]);
        System.out.println("Tiempo 5: " + array[4]);
        System.out.println("Lenght: " + array.length);
    }//GEN-LAST:event_btnPrepararseActionPerformed

    ////////////////////EVENTOS DE TECLADO GLOBAL////////////////////
    public void keyPressed(KeyEvent e){
        System.out.println("Tecla: "+ e.getKeyChar()+"\n");

    }
    public void keyTyped(KeyEvent arg0) {
        //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
    public void keyReleased(KeyEvent arg0) {
        //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
    

    private void iniciarCronometro(){//CICLO FOR DE CADA SEGUNDO
        //lblContadorGlobal.setText("Tiempo: " + it);
        
        l1.setText("Tiempo: " + it);
        
        System.out.println(it);
        it++;
        
        if(array[i]==time){
            lbl1.setLocation((distancia), 20);
            distancia+=815/time;
            if(distancia>=865){
                distancia=50;
                i++;
            }
        }
            
        if(array[i]==time2){
            lbl2.setLocation((distancia), 120);
            distancia+=815/time2;
            if(distancia>=865){
                distancia=50;
                i++;
            }
        }
            
        if(array[i]==time3){
            lbl3.setLocation((distancia), 220);
            distancia+=815/time3;
            if(distancia>=865){
                distancia=50;
                i++;
            }
        }
            
        if(array[i]==time4){
            lbl4.setLocation((distancia), 320);
            distancia+=815/time4;
            if(distancia>=865){
                distancia=50;
                i++;
            }
        }
            
        if(array[i]==time5){
            lbl5.setLocation((distancia), 420);
            distancia+=815/time5;
            if(distancia>=865){
                distancia=50;
                i++;
            }
        }
            

        
        if(i>5){
            mTimer.stop();
        }
        
        if(it==time+time2+time3+time4+time5+3){
            mTimer.stop();
        }
        
    }
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainProgram().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciar;
    private javax.swing.JButton btnPrepararse;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lbl4;
    private javax.swing.JLabel lbl5;
    private javax.swing.JPanel pnlMeta;
    // End of variables declaration//GEN-END:variables


}
