
package mlq;

import java.awt.Image;
import java.awt.Label;
import java.awt.event.ActionEvent;
import java.util.ArrayList;
import java.util.TimerTask;
import javax.swing.Timer;
import javax.swing.JOptionPane;
import javax.swing.JTabbedPane;
import javax.swing.table.DefaultTableModel;
import java.util.Random;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import javax.swing.ImageIcon;
import javax.swing.JTextField;

public class MainProgram extends javax.swing.JFrame implements KeyListener {
    Random random = new Random();
    private Timer mTimer;
    private int contloc=0;//contador local
    private int contglobal=0;//contador local
    private int tiempo=0;
    private int temprest=0;
    private int it=0;
    private int it2=0;
    private int it3=0;
    private int distancia=50;//distancia
    private int distancia2=50;//distancia
    private int distancia3=50;//distancia
    private int time=0,time2=0,time3=0;//CINCO NUMEROS ALEATORIOS
    private int iterator_tabla1=0;
    private int[] array=new int[5];
    private int[] array1=new int[3];
    private int[] array2=new int[3];
    private int[] array3=new int[3];
    private int i=0;
    private int i2=0;
    private int i3=0;
    private Label l1;
    //ArrayList <Proceso> procesos;
    //Proceso pr;
    
    ImageIcon imageIconPonyta= new ImageIcon("ponyta.png");
    Image imagePonyta = imageIconPonyta.getImage();
    Image modPonyta = imagePonyta.getScaledInstance(75, 75, java.awt.Image.SCALE_SMOOTH);
    
    ImageIcon imageIconPidove= new ImageIcon("pidove.png");
    Image imagePidove = imageIconPidove.getImage();
    Image modPidove = imagePidove.getScaledInstance(75, 75, java.awt.Image.SCALE_SMOOTH);
    
    ImageIcon imageIconMudbray= new ImageIcon("mudbray.png");
    Image imageMudbray = imageIconMudbray.getImage();
    Image modMudbray = imageMudbray.getScaledInstance(75, 75, java.awt.Image.SCALE_SMOOTH);
        
    public MainProgram(){
        
        //procesos = new ArrayList<>();
        imageIconPonyta = new ImageIcon(modPonyta);
        imageIconPidove = new ImageIcon(modPidove);
        imageIconMudbray = new ImageIcon(modMudbray);
        
        
        initComponents();
        mTimer = new Timer(1000, (ActionEvent e) -> {
                iniciarCronometro();  
            });
        
        addKeyListener(this);
        setFocusable(true);
        //btnIniciar.setVisible(true);
        this.setVisible(true);
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lbl1 = new javax.swing.JLabel();
        btnIniciar = new javax.swing.JButton();
        lbl2 = new javax.swing.JLabel();
        lbl3 = new javax.swing.JLabel();
        lbl4 = new javax.swing.JLabel();
        lbl5 = new javax.swing.JLabel();
        pnlMeta = new javax.swing.JPanel();
        btnPrepararse = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        jPanel2.setBackground(new java.awt.Color(102, 153, 255));

        btnIniciar.setText("INICIAR");
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });

        pnlMeta.setBackground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout pnlMetaLayout = new javax.swing.GroupLayout(pnlMeta);
        pnlMeta.setLayout(pnlMetaLayout);
        pnlMetaLayout.setHorizontalGroup(
            pnlMetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );
        pnlMetaLayout.setVerticalGroup(
            pnlMetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
        );

        btnPrepararse.setText("PREPARARSE");
        btnPrepararse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrepararseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(222, Short.MAX_VALUE)
                        .addComponent(btnPrepararse, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(btnIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(292, 292, 292))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl2)
                            .addComponent(lbl1)
                            .addComponent(lbl3)
                            .addComponent(lbl4)
                            .addComponent(lbl5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(pnlMeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnPrepararse, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(pnlMeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lbl1)
                        .addGap(69, 69, 69)
                        .addComponent(lbl2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl3)
                        .addGap(80, 80, 80)
                        .addComponent(lbl4)
                        .addGap(97, 97, 97)
                        .addComponent(lbl5)
                        .addGap(111, 111, 111))))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
        lbl1.setLocation(20, 20);
        lbl2.setLocation(20, 170);
        lbl3.setLocation(20, 320);
        pnlMeta.setLocation(850, 20);
        
        lbl1.setText("");
        lbl1.setIcon(imageIconPonyta);
        lbl2.setText("");
        lbl2.setIcon(imageIconPidove);
        lbl3.setText("");
        lbl3.setIcon(imageIconMudbray);
        
        distancia=50;
        distancia2=50;
        distancia3=50;
        
        int n = array.length;
        
        mTimer.start();
    }//GEN-LAST:event_btnIniciarActionPerformed

    private void btnPrepararseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrepararseActionPerformed
        lbl1.setLocation(20, 20);
        lbl2.setLocation(20, 170);
        lbl3.setLocation(20, 320);
        pnlMeta.setLocation(850, 20);
        
        lbl1.setText("");
        lbl1.setIcon(imageIconPonyta);
        lbl2.setText("");
        lbl2.setIcon(imageIconPidove);
        lbl3.setText("");
        lbl3.setIcon(imageIconMudbray);
        
        int j=0;
        
        l1 = new Label ("Tiempo: 0");
        l1.setLocation(50, 50);
        
        Random dado = new Random();
        
        
        for(j=0;j<3; j++){
            time=dado.nextInt(10-5+1)+7;
            array1[j]=time;
            
            time2=dado.nextInt(10-5+1)+7;
            array2[j]=time2;
            
            time3=dado.nextInt(10-5+1)+7;
            array3[j]=time3;
        }
        
        
              System.out.println("Planificador 1, 1: " + array1[0]);
              System.out.println("Planificador 1, 2: " + array1[1]);
              System.out.println("Planificador 1, 3: " + array1[2]+"\n");
              System.out.println("Planificador 2, 1: " + array2[0]);
              System.out.println("Planificador 2, 2: " + array2[1]);
              System.out.println("Planificador 2, 3: " + array2[2]+"\n");
              System.out.println("Planificador 3, 1: " + array3[0]);
              System.out.println("Planificador 3, 2: " + array3[1]);
              System.out.println("Planificador 3, 3: " + array3[2]+"\n");
        
        

    }//GEN-LAST:event_btnPrepararseActionPerformed

    ////////////////////EVENTOS DE TECLADO GLOBAL////////////////////
    public void keyPressed(KeyEvent e){
        System.out.println("Tecla: "+ e.getKeyChar()+"\n");

    }
    public void keyTyped(KeyEvent arg0) {
        //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
    public void keyReleased(KeyEvent arg0) {
        //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
    

    private void iniciarCronometro(){//CICLO FOR DE CADA SEGUNDO
        //lblContadorGlobal.setText("Tiempo: " + it);
        //l1.setText("Tiempo: " + it);
        //System.out.println(it2);
        
        it++;
        it2++;
        it3++;
                
        if(i<3){
            if(it<=array1[i]+1){
                distancia+=815/array1[i];
                lbl1.setLocation((distancia), 20);
                if(it==array1[i]+1){
                    //System.out.println("NUMERO i = " + i);
                    i++;
                    distancia=50;
                    lbl1.setLocation((distancia), 20);
                    it=0;
                }
            }
        }
        
        if(i2<3){
            if(it2<=array2[i2]+1){
                distancia2+=815/array2[i2];
                lbl2.setLocation((distancia2), 170);
                if(it2==array2[i2]+1){
                    //System.out.println("NUMERO i = " + i);
                    i2++;
                    distancia2=50;
                    lbl2.setLocation((distancia2), 170);
                    it2=0;
                }
            }
        }
        
        
        if(i3<3){
            if(it3<=array3[i3]+1){
                distancia3+=815/array3[i3];
                lbl3.setLocation((distancia3), 320);
                if(it3==array3 [i3]+1){
                    //System.out.println("NUMERO i = " + i);
                    i3++;
                    distancia3=50;
                    lbl3.setLocation((distancia3), 320);
                    it3=0;
                }
            }
        }

        
        if(i>3&&i2>3&&i3>3){
            mTimer.stop();
        }
        
    }
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainProgram().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciar;
    private javax.swing.JButton btnPrepararse;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lbl4;
    private javax.swing.JLabel lbl5;
    private javax.swing.JPanel pnlMeta;
    // End of variables declaration//GEN-END:variables


}
